package dev.solsynth.cloudysky.ui.theme

import androidx.compose.ui.graphics.Color

// Seed-inspired sky palette (fallback when dynamic color is unavailable)

// Light
val SkyPrimaryLight = Color(0xFF2E5A88)
val SkyOnPrimaryLight = Color(0xFFFFFFFF)
val SkyPrimaryContainerLight = Color(0xFFD0E4FF)
val SkyOnPrimaryContainerLight = Color(0xFF001D36)

val SkySecondaryLight = Color(0xFF535F70)
val SkyOnSecondaryLight = Color(0xFFFFFFFF)
val SkySecondaryContainerLight = Color(0xFFD7E3F7)
val SkyOnSecondaryContainerLight = Color(0xFF101C2B)

val SkyTertiaryLight = Color(0xFF6B5778)
val SkyOnTertiaryLight = Color(0xFFFFFFFF)
val SkyTertiaryContainerLight = Color(0xFFF2DAFF)
val SkyOnTertiaryContainerLight = Color(0xFF251431)

val SkyErrorLight = Color(0xFFBA1A1A)
val SkyOnErrorLight = Color(0xFFFFFFFF)
val SkyErrorContainerLight = Color(0xFFFFDAD6)
val SkyOnErrorContainerLight = Color(0xFF410002)

val SkyBackgroundLight = Color(0xFFF8F9FF)
val SkyOnBackgroundLight = Color(0xFF191C20)
val SkySurfaceLight = Color(0xFFF8F9FF)
val SkyOnSurfaceLight = Color(0xFF191C20)
val SkySurfaceVariantLight = Color(0xFFDFE2EB)
val SkyOnSurfaceVariantLight = Color(0xFF43474E)
val SkyOutlineLight = Color(0xFF73777F)
val SkyOutlineVariantLight = Color(0xFFC3C6CF)
val SkyInverseSurfaceLight = Color(0xFF2E3135)
val SkyInverseOnSurfaceLight = Color(0xFFEFF0F7)
val SkyInversePrimaryLight = Color(0xFF9ECAFF)
val SkySurfaceDimLight = Color(0xFFD9DAE0)
val SkySurfaceBrightLight = Color(0xFFF8F9FF)
val SkySurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SkySurfaceContainerLowLight = Color(0xFFF2F3FA)
val SkySurfaceContainerLight = Color(0xFFEDEDF4)
val SkySurfaceContainerHighLight = Color(0xFFE7E8EE)
val SkySurfaceContainerHighestLight = Color(0xFFE1E2E8)

// Dark
val SkyPrimaryDark = Color(0xFF9ECAFF)
val SkyOnPrimaryDark = Color(0xFF003258)
val SkyPrimaryContainerDark = Color(0xFF0F4470)
val SkyOnPrimaryContainerDark = Color(0xFFD0E4FF)

val SkySecondaryDark = Color(0xFFBBC7DB)
val SkyOnSecondaryDark = Color(0xFF253140)
val SkySecondaryContainerDark = Color(0xFF3B4858)
val SkyOnSecondaryContainerDark = Color(0xFFD7E3F7)

val SkyTertiaryDark = Color(0xFFD6BEE4)
val SkyOnTertiaryDark = Color(0xFF3B2948)
val SkyTertiaryContainerDark = Color(0xFF523F5F)
val SkyOnTertiaryContainerDark = Color(0xFFF2DAFF)

val SkyErrorDark = Color(0xFFFFB4AB)
val SkyOnErrorDark = Color(0xFF690005)
val SkyErrorContainerDark = Color(0xFF93000A)
val SkyOnErrorContainerDark = Color(0xFFFFDAD6)

val SkyBackgroundDark = Color(0xFF111418)
val SkyOnBackgroundDark = Color(0xFFE1E2E8)
val SkySurfaceDark = Color(0xFF111418)
val SkyOnSurfaceDark = Color(0xFFE1E2E8)
val SkySurfaceVariantDark = Color(0xFF43474E)
val SkyOnSurfaceVariantDark = Color(0xFFC3C6CF)
val SkyOutlineDark = Color(0xFF8D9199)
val SkyOutlineVariantDark = Color(0xFF43474E)
val SkyInverseSurfaceDark = Color(0xFFE1E2E8)
val SkyInverseOnSurfaceDark = Color(0xFF2E3135)
val SkyInversePrimaryDark = Color(0xFF2E5A88)
val SkySurfaceDimDark = Color(0xFF111418)
val SkySurfaceBrightDark = Color(0xFF37393D)
val SkySurfaceContainerLowestDark = Color(0xFF0C0E12)
val SkySurfaceContainerLowDark = Color(0xFF191C20)
val SkySurfaceContainerDark = Color(0xFF1D2024)
val SkySurfaceContainerHighDark = Color(0xFF282A2E)
val SkySurfaceContainerHighestDark = Color(0xFF323539)
